### ISSUE TITLE
定时器使用问题请教一下

### ISSUE THREAD

**Issue by maxbad** [williamxin/cron_timer#1]
如果设定了2个定时器,A是每分钟的第5秒执行,B是每分钟的第6秒执行, 如果A的执行时间超过了1秒钟, B就不会触发了.这个可以改进一下吗.

**Comment by williamxin** [comment]
这是因为任务的执行阻塞了线程，导致时间判断不准确，这个问题我一般都是做一个消息队列，在定时器里面生产消息，在逻辑线程（我一般都是主线程）中消费消息。

根据你的描述，你这个场景很适合另外开一个线程去处理任务，定时器线程发送消息给你的任务线程
